version: '3.7'

services:
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    # раскомментить для внесения изменений
    # build: .
    # и закомментить 'image'
    image: estlyx/social_network
    command: python /usr/src/social_network_2.0/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/social_network_2.0
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: